import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Homepage</Link>
        </li>
        <li>
          <Link to="/signuppage">Signuppage</Link>
        </li>
        <li>
          <Link to="/loginpage">Loginpage</Link>
        </li>
        <li>
          <Link to="/loansucces">Loansucces</Link>
        </li>
        <li>
          <Link to="/personalinfo">PersonalInfo</Link>
        </li>
        <li>
          <Link to="/employmentdetails">Employmentdetails</Link>
        </li>
        <li>
          <Link to="/particularsofexistingloan">Particularsofexistingloan</Link>
        </li>
        <li>
          <Link to="/upload">Upload</Link>
        </li>
        <li>
          <Link to="/errorpage">ErrorPage</Link>
        </li>
        <li>
          <Link to="/applicationsucces">Applicationsucces</Link>
        </li>
        <li>
          <Link to="/bankingdetails">BankingDetails</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
